const RouteName = {
    SPLSH: "SplashScreen",
    SWIPER_SCREEN: "Swiperscreen",
    LOGIN_SCREEN: "LoginScreen",
    REGISTER_SCREEN: "Register",
    OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
    HOME_SCREEN: "HomeScreen",
    REGIATRAION_SUCCESSFULL: "RegistrationSuccessful",
    HOME_TAB: 'Home',
    MESSAGE_TAB: 'Messages',
    SAVE_JOB_LIST: 'Save Jobs',
    PROFILE_TAB: 'Profile',
    JOB_TYPES_SCREEN: 'JobTypeScreen',
    JOB_TIMES_SCREEN: 'JobTimesScreen',
    SERLECT_JOB_AND_LOCATION: 'SelectJobandLocation',
    SELECT_LANGUAGE: 'TranslationScreen',
    APPLY_JOB: 'ApplyJob',
    APPLY_JOB_DETAILS: 'ApplyJobDetails',
    Resume_And_Portfolio: 'ResuameAndPortFolio',
    JOB_DETAILS_SCREEN: 'JobDetailsScreen',
    Forget_Password: 'ForgotPassword',
    CHAT_SCREEN: 'Chatscreen',
    FEATURED_ALL_JOB: 'FeaturedAllJob',
    SETTING_SCREEN: 'SettingsScreen',
}
export default RouteName;