const images = {
   First_Swiper: require('./LottieAnimation/FirstSwiper.json'),
   Two_Swiper: require('./LottieAnimation/TwoSwiper.json'),
   Three_Swiper: require('./LottieAnimation/ThreeSwiper.json'),
   Splash_Swiper: require('./LottieAnimation/SplashScreen.json'),
   Account_created: require('./LottieAnimation/Accountcreated.json'),
   UxDisigner_Digner: require('./LottieAnimation/UxDisigner.json'),
   Facebook_animation: require('./LottieAnimation/Facebook.json'),
   Left_aerrow_details: require('./LottieAnimation/Leftaerrows.json'),
   Likeanimation: require('./LottieAnimation/LikeImages.json'),
   Languageanimation: require('./LottieAnimation/languageanimation.json'),
   App_logo: require('./one_fifty.png'),
   Color_picker_image: require('./colorpicker.png'),
   Google_image: require('./googleicon.png'),
   Codingimage_one: require('./fourty_five.png'),
   Codingimage_two: require('./fourty_five.png'),
   Codingimage_three: require('./fourty_five.png'),
   UXdEsigner_one: require('./fourty_five.png'),
   UXdEsigner_two: require('./sixty.png'),
   UXdEsigner_three: require('./sixty.png'),
   UxDisignerfourt_file: require('./sixty.png'),
   User_image_one_profile: require('./sixty.png'),
   Chat_image_one: require('./seventy.png'),
   Chat_image_two: require('./seventy.png'),
   Chat_image_three: require('./seventy.png'),
   Chat_image_four: require('./seventy.png'),
   Chat_image_five: require('./seventy.png'),
   Chat_image_six: require('./seventy.png'),
   Chat_image_saven: require('./seventy.png'),
   Chat_image_aeight: require('./seventy.png'),
}
export default images;